name: Tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    - name: Run tests with coverage
      env:
        CLOCKIFY_API_KEY: ${{ secrets.CLOCKIFY_API_KEY }}
        CLOCKIFY_WORKSPACE_ID: ${{ secrets.CLOCKIFY_WORKSPACE_ID }}
      run: |
        python -m pytest --cov=clockify_sdk --cov-report=xml
    - name: Run type checking
      run: |
        mypy clockify_sdk
    - name: Run linting
      run: |
        ruff check .
        black --check .
        isort --check .